apiVersion: v1
kind: Service
metadata:
  name: image-captioning-service
spec:
  selector:
    app: image-captioning
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
